# Generated by Django 3.0.8 on 2021-02-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210130_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
